#################################################################
# CONFIGURAÇÕES GERAIS DA APLICAÇÃO
#################################################################
quarkus.http.port=8082

# Configurações para mitigar thread blocked no dev mode
quarkus.vertx.event-loops-pool-size=2
quarkus.vertx.worker-pool-size=20
quarkus.vertx.max-event-loop-execute-time=10s

#################################################################
# CONFIGURAÇÃO DO CLIENTE REST (GROQ)
#################################################################
# A chave "groq-api" deve casar com o configKey na interface GroqRestClient
quarkus.rest-client.groq-api.url=https://api.groq.com/openai/v1
quarkus.rest-client.groq-api.connect-timeout=10000
quarkus.rest-client.groq-api.read-timeout=30000

#################################################################
# SEGURANÇA (JWT)
#################################################################
quarkus.smallrye-jwt.enabled=true
quarkus.smallrye-jwt.signer-secret=ZmF0ZWMtc2VjcmV0LXRlc3Q=
quarkus.smallrye-jwt.expiration=3600

#################################################################
# OPENAPI / SWAGGER
#################################################################
quarkus.smallrye-openapi.info-title=FATEC AI BOT Backend API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.path=/openapi
%dev.quarkus.swagger-ui.always-include=true
%dev.quarkus.swagger-ui.path=/swagger

#################################################################
# INFRAESTRUTURA (DYNAMO)
#################################################################
app.dynamodb.table-name=fatec-ai-bot-core

# Configuração de ambiente de desenvolvimento (LocalStack)
%dev.quarkus.dynamodb.endpoint-override=http://localhost:4566
%dev.quarkus.dynamodb.aws.region=us-east-1
%dev.quarkus.dynamodb.aws.credentials.type=static
%dev.quarkus.dynamodb.aws.credentials.static-provider.access-key-id=test
%dev.quarkus.dynamodb.aws.credentials.static-provider.secret-access-key=test

# Configuração de produção
%prod.quarkus.dynamodb.aws.region=${AWS_REGION:us-east-1}
%prod.quarkus.dynamodb.aws.credentials.type=default

# Configurações da IA
groq.api.key=${GROQ_API_KEY}